# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/MIPS_CPU/Basys3_Master.xdc

# IP: ip/ram/ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram || ORIG_REF_NAME==ram}]

# IP: ip/rom/rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom || ORIG_REF_NAME==rom}]

# IPX: ip/rom.xcix
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom || ORIG_REF_NAME==rom}]

# XDC: ip/ram/ram_ooc.xdc

# XDC: ip/rom/rom_ooc.xdc
